import { StyleSheet } from "react-native";

export const getStyles = (theme: any) =>
  StyleSheet.create({
    sidebar: {
      flex: 1,
      backgroundColor: theme.secondaryBackgroundColor,
      borderRightWidth: 1,
      borderRightColor: theme.borderColor,
      padding: 20,
      paddingTop: 40,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 30,
    },
    title: {
      fontSize: 24,
      fontFamily: theme.boldFont,
      color: theme.textColor,
    },
    closeButton: {
      padding: 5,
    },
    walletSection: {
      marginBottom: 30,
    },
    walletCard: {
      backgroundColor: theme.secondaryBackgroundColor,
      borderRadius: 16,
      padding: 16,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.borderColor,
    },
    walletIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(148, 163, 184, 0.16)",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    walletInfo: {
      flex: 1,
    },
    walletLabel: {
      fontSize: 12,
      color: theme.mutedForegroundColor,
      fontFamily: theme.lightFont,
      marginBottom: 4,
    },
    walletAddress: {
      fontSize: 16,
      color: theme.textColor,
      fontFamily: theme.semiBoldFont,
      letterSpacing: 0.5,
    },
    menuSection: {
      flex: 1,
    },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderRadius: 10,
      marginBottom: 6,
    },
    menuText: {
      fontSize: 16,
      color: theme.textColor,
      fontFamily: theme.regularFont,
      marginLeft: 16,
    },
    footer: {
      borderTopWidth: 1,
      borderTopColor: theme.borderColor,
      paddingTop: 20,
    },
    disconnectButton: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: "rgba(255, 68, 68, 0.1)",
    },
    disconnectText: {
      fontSize: 16,
      color: "#ff4444",
      fontFamily: theme.semiBoldFont,
      marginLeft: 12,
    },
    conversationsSection: {
      flex: 1,
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 13,
      color: theme.textColor,
      fontFamily: theme.semiBoldFont,
      opacity: 0.6,
      marginBottom: 12,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    conversationsList: {
      flex: 1,
      marginBottom: 12,
    },
    conversationItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 10,
      marginBottom: 6,
      backgroundColor: theme.secondaryBackgroundColor,
    },
    conversationInfo: {
      flex: 1,
      marginLeft: 12,
    },
    conversationTitle: {
      fontSize: 14,
      color: theme.textColor,
      fontFamily: theme.regularFont,
      marginBottom: 2,
    },
    conversationModel: {
      fontSize: 11,
      color: theme.textColor,
      fontFamily: theme.lightFont,
      opacity: 0.5,
    },
    allChatsButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.borderColor,
    },
    allChatsText: {
      fontSize: 14,
      color: theme.tintColor,
      fontFamily: theme.mediumFont,
    },
  });
